# Generated by Django 5.0.7 on 2024-07-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
